class LibParse:
    PROGRAM = 'APP'
    STATEMENT = 'STATEMENT'

    EXPRESSION_ST = 'EXPRESSION_ST'
    EXPRESSION = 'EXPRESSION'
    COMPOUND_ST = 'COMPOUND_ST'

    EXPRESSION_INNER = 'EXPRESSION ( ... )'

    VARIABLE = 'VARIABLE'
    NUMBER = 'NUMBER'

    SET = 'SET'
    ADD = 'ADD'
    SUB = 'SUB'
    MUL = 'MUL'
    DIV = 'DIV'

    IF = 'IF'
    VAR_INT = 'VAR_INT'

    NOOP = 'NOOP'
    LIST = 'LIST'

