class LibParse:
    PROGRAM = 'Program'
    STATEMENT = 'STATEMENT'
    EXPRESSION_ST = 'EXPRESSION_ST'
    EXPRESSION = 'EXPRESSION'
    EXPRESSION_INNER = 'EXPRESSION ( ... )'
    VARIABLE = 'VARIABLE'
    INTEGER = 'INTEGER'
    FLOAT = 'FLOAT'
    SET = 'SET'
    ADD = 'ADD'
    MUL = 'MUL'
    DIV = 'DIV'
    MOD = 'MOD'
    SUB = 'SUB'
    IF = 'IF'
    FOR = 'FOR'
    NOOP = 'NOOP'
